name: Docker CI

on:
  push:
    branches:
      - main
      - airflow-kafka-basic
  pull_request:
    branches:
      - main
      - airflow-kafka-basic
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_COMPOSE_PATH: .
      PYTHON_CODE_DIRS: "airflow postgres_consumer clickhouse_consumer"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version # Verify installation

      - name: Validate Docker Compose Configuration
        working-directory: ${{ env.DOCKER_COMPOSE_PATH }}
        run: docker-compose config

      - name: Build Docker Compose Stack
        working-directory: ${{ env.DOCKER_COMPOSE_PATH }}
        run: docker-compose build

      - name: Run Mypy Type Checking
        run: |
          for dir in ${{ env.PYTHON_CODE_DIRS }}; do
            echo "Running mypy on $dir..."
            mypy "$dir"
          done

      - name: Run Flake8 Linting
        run: |
          for dir in ${{ env.PYTHON_CODE_DIRS }}; do
            echo "Running flake8 on $dir..."
            flake8 "$dir"
          done
